# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.kernelParams = [ "video=2560x1440@165" ];
  boot.extraModulePackages = [ ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.timeout = 2;

  console = {
    earlySetup = true;
    packages = [ pkgs.powerline-fonts ];
    font = "ter-powerline-v24b";
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/63725ab0-fc6c-4c43-85e1-f650d8da7fb5";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B212-CAA9";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fa637dbd-b08e-4db3-8c5e-969a30bc9500"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s3.useDHCP = lib.mkDefault true;

#  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
#  virtualisation.virtualbox.guest.enable = true;

# TODO https://discourse.nixos.org/t/nixos-shell-in-nixos-vm-does-not-seem-to-be-recognizing-store-paths/14377/2
nix.nixPath = [
    "nixpkgs=${pkgs.path}"
];

virtualisation.vmVariant = {
    virtualisation.memorySize = 2048;
    virtualisation.cores = 2;
    virtualisation.resolution = {
      x = 2560;
      y = 1440;
    };
    virtualisation.qemu.options = [
      # Better display option
      "-vga none -device qxl-vga,vgamem_mb=32"
      # Enable copy/paste
      # https://www.kraxel.org/blog/2021/05/qemu-cut-paste/
      "-chardev qemu-vdagent,id=ch1,name=vdagent,clipboard=on"
      "-device virtio-serial-pci"
      "-device virtserialport,chardev=ch1,id=ch1,name=com.redhat.spice.0"
    ];
  };

}
